name: Automated Test
on: [push]
jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Produce Test 1 Output
        run: python find_lowest_number.py test_data/test1_input.txt test1_input.txt
      - name: Test 1
        run: diff test_data/test1_expected.txt test1_input.txt
